### ISSUE TITLE
Running smee-client as a service

### ISSUE THREAD

**Issue by levimatheri** [probot/smee-client#118]
Is it possible to run smee-client as a service on Windows? I tried writing a bat script that would call the smee command but after building an exe and creating the service, Windows would throw an error 1053: The service did not respond to the start or control request in a timely fashion.

**Comment by JasonEtco** [comment]
@levimatheri you can look into [`pm2`](https://www.npmjs.com/package/pm2) and using the programmatic API of smee-client:

https://github.com/probot/smee-client/blob/2eb82ce58dbb66dc2fbcbadc7c81c6b0bcf9df2f/index.js#L75

Past that, running `smee-client` as a service isn't something we directly support and I don't think we need to. The building blocks are there for you to set it up 😄 I'm going to close this issue as there are no action items.

**Comment by levimatheri** [comment]
@JasonEtco You're right. I just chose to use [this](https://www.npmjs.com/package/qckwinsvc) and it works too!
