### ISSUE TITLE
smee not trigging Jenkins job

### ISSUE THREAD

**Issue by sushilbh** [probot/smee-client#120]
I am newbie to smee. I setup my Jenkins in a docker container running on port `8080`, i first installed and configured smee. I started the smee client and it does says `Forwarding https://smee.io/XXXXXXXXXX to 8080`. I also have webhook setup correctly, when i pushed changes to my git repo _Webhook Deliveries_ does says something is being pushed. The purpose of having smee is Jenkins job needs to trigger automatically once i pushed the code to my repo. Not sure where i am having problem. is it something my Jenkins being run on docker container or some other configuration error? Thank you in advance.

**Comment by levimatheri** [comment]
Is Jenkins polling? Try using GitHub Branch Source plugin. You will need to write Jenkinsfile pipeline scripts but it works. Alternatively, take a look at BlueOcean plugin

**Comment by sushilbh** [comment]
Added 

properties([pipelineTriggers([githubPush()])]) in the Jenkinsfile

It started working fine!
