### ISSUE TITLE
Smee seems to reformat JSON without updating Content-Length header

### ISSUE THREAD

**Issue by viphe** [probot/smee-client#136]
Hi,

I am using smee-client in front of a custom Node app. During my tests using `curl`, I noticed the following kind of error from it:

```
Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at Socket.socketOnEnd (_http_client.js:440:23)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  response: undefined
}
```

By observing the payload, I finally realized that the 'Content-Length' header coming from smee client was still equal to what my curl command was sending whereas the JSON payload itself had been reformatted to a compact format.

This leads my app to hang, waiting for more bytes to come from the smee client:
```
BadRequestError: request aborted
    at IncomingMessage.onAborted (/app/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:210:5)
    at abortIncoming (_http_server.js:492:9)
    at socketOnClose (_http_server.js:485:3)
    at Socket.emit (events.js:215:7)
    at TCP.<anonymous> (net.js:658:12)
```

Simple example to reproduce:

```bash
curl https://smee.io/XXXXX --data '{ }' -H 'Content-Type: application/json'
```

The `tcpdump` trace of the corresponding HTTP request coming from smee client to my app:
```
POST / HTTP/1.1
host: smee.io
Accept-Encoding: gzip, deflate
user-agent: curl/7.54.0
content-type: application/json
connection: close
accept: */*
x-request-id: 3e3de197-3708-4dd2-8202-21c3f3e6ccd5
x-forwarded-for: 70.36.61.12
x-forwarded-proto: https
x-forwarded-port: 443
via: 1.1 vegur
connect-time: 0
x-request-start: 1572802450843
total-route-time: 0
content-length: 3
timestamp: 1572802450846

{}
```

I have no idea what part of the pipeline is at fault but I would expect that either the JSON format should be left alone or that the content length should be recalculated accordingly to the new format.

smee client version: 1.1.0

Thanks.
Philippe

**Comment by jaimefps** [comment]
I'm having this problem with the same exact stack trace:

```
Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at Socket.socketOnEnd (_http_client.js:440:23)
    at Socket.emit (events.js:228:7)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

Is there any reason you cannot execute a GET request from inside an Express.js router.put()?
I have two routes. The exact same api call works in a `router.get()` route and hangs in the `router.put()`.

This works:
```
router.get('/:id', async () => {
  let result;
  try {
    result = await axios({ method:'get', url: '/some-url' });
  } catch(error) {
    res.status(500).send(new Error('myError');
  }
  res.send({ result });
});```

This does NOT work:
```
router.put('/:id', async () => {
  let result;
  let finalResult;

  try {
    result = await axios({ method:'get', url: '/some-url' });
  } catch(error) {
    res.status(500).send(new Error('myError');
  }

  // logic based on the result of the above GET determines what the value of `finalResult`
  finalResult = { some: 'data' };

  res.send({ finalResult });
});```

Even though `axios({ method:'get', url: '/some-url' })` is the exact same in both routes, it works in one and not the other. The `router.put()` route always hangs for a long time and eventually Node outputs the stack trace above.

Appreciate any help, I've spent over a day trying to debug this and have found no solution.

**Comment by chrisdothtml** [comment]
Just spent a couple hours debugging before finding this issue :(

Don't have any proposed solutions, but can confirm everything in the issue description. Everything I found on this issue wrt express said that this happens when the content length doesn't match the actual content, so it does seem that smee is violating this in some way

**Comment by Frechetta** [comment]
I have also run into this issue. My quick, hacky fix was to add `const data_len = JSON.stringify(data.body).length` before the `delete data.body` line and ```req.set('content-length', `${data_len}`)``` before `req.end(....)` in index.js.

**Comment by FerLuisxd** [comment]
still relevant 👍 , happened to me today

**Comment by cortexcompiler** [comment]
I worked around this by adding a `delete data['content-length']` to the client code:

- https://github.com/probot/smee-client/blob/master/index.ts#L48

This prevents the "content-length" header from being set and `superagent` or something in the stack seems to figure out fine.  For me, I noticed the length is one shorter than was passed from the event stream.

I will say that a verbose or debug logging option could have made tracking this down much easier.

**Comment by DavidEllis008** [comment]
I found using the `-t` flag instead of the `--path` and `--port` got rid of this issue for me. 
I moved from using 
```smee --url https://smee.io/webhook --path /ghprbhook/ --port 9999 &```
to this
```smee --url https://smee.io/webhook -t http://localhost:9999/ghprbhook/ &```
solved this problem for me.
