### ISSUE TITLE
No changelog for v1.2.0

### ISSUE THREAD

**Issue by skjnldsv** [probot/smee-client#157]
https://github.com/probot/smee-client/releases

**Comment by skjnldsv** [comment]
yep still relevant

**Comment by dhs-rec** [comment]
BTW: Latest version is 1.2.2, bit it hasn't even been tagged/released.

**Comment by tcbyrd** [comment]
Sorry for missing this earlier. Updated with [v1.2.3](https://github.com/probot/smee-client/releases/tag/v1.2.3)
