### ISSUE TITLE
Doesn't appear to work for discord verification

### ISSUE THREAD

**Issue by JustinBeckwith** [probot/smee-client#185]
Greetings folks!  I'm such a huge fan of using smee for GitHub bot development, that I decided to try using it as a local tunnel to build a Discord bot. I am following along with this blog post:
https://ianmitchell.dev/blog/creating-a-discord-http-slash-command-bot-with-fastify

The official documentation is here:
https://discord.com/developers/docs/interactions/receiving-and-responding#receiving-an-interaction

The docs here suggest using [ngrok](https://ngrok.com/), but I was more familiar with smee so I chose that.  Sadly ... I am running into an issue where the verification of the discord webhook url does not succeed.  It's nearly impossible for me to debug, as I respond to a specific `PING` with a `PONG`, and the discord server rejects the verification.  When I use the same exact code with ngrok as the proxy, everything seems to work fine.  

Let me know if there's any more info I can provide to make debugging this one easier!

**Comment by Uzlopak** [comment]
smee does not return the payload of the response. It is not a fully fledged proxy like ngrok
