### ISSUE TITLE
Host header smee.io causing Jenkins webhook to fail

### ISSUE THREAD

**Issue by dhanar10** [probot/smee-client#187]
This issue starts happening to me today. 

Based on my limited experiment, Jenkins BitBucket PPR webhook will fail with 404 error when it sees "host: smee.io" in request header. Removing the "host: smee.io" in request header works (I use curl to simulate this).

This is weird since smee-client has no changes for so long and the BitBucket PPR webhook plugin is last updated 3 months ago.

Does smee-client always include "host: smee.io" when invoking target webhook? If yes, then maybe an option to exlude "host: smee.io" when invoking target webhook would be nice.

**Comment by amarnath552** [comment]
Hi All,

I am trying to use Smee client to trigged the Job in Jenkins from git webhook. I created the new job in Jenkins and commit any change in the git, I am able to triggered the Job in Jenkins. When I tried to made any change in the git 2nd time, smee getting the response from git but job not triggered in the Jenkins. If removed the 1st build in the Jenkins and commit the changes in git it's working. Can any once please suggest or provide any solution on this issue.
smee --url https://smee.io/XXXXXxxxxxxx --target http://127.0.0.1:8080/github-webhook/

**Comment by bmerry** [comment]
This is also causing problems when using an https target: one gets a certificate error like "Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: smee.io. is not in the cert's altnames: DNS:xxx" where xxx is the target hostname.
