### ISSUE TITLE
Proxy support for smee client

### ISSUE THREAD

**Issue by ojoggerst** [probot/smee-client#194]
**Problem description**

We would like to use the smee client behind a proxy. Currently, there is no possibility to add a proxy URL to the smee client, so that all outgoing connections would be proxied through a specific server.

**Solution**
1. Use superagent proxy (https://www.npmjs.com/package/superagent-proxy)
2. Use global agent (https://www.npmjs.com/package/global-agent)

Option one needs code changes and seems a bit more cumbersome. 

Option two is fairly simple and only needs global agent dependencies and one line in index.js to import the package.

After that you can do:
`GLOBAL_AGENT_HTTP_PROXY=http://<proxy-host>:<proxy-port> node ./bin/smee.js -u https://<smee-server>/<token>`

Please check PR: https://github.com/probot/smee-client/pull/195

**Comment by jakobkolb** [comment]
I need this feature to be able to use smee in our environment. Would love to see it become reality ❤️

**Comment by wolfy1339** [comment]
You can pass in your own custom fetch wrapper. NodeJS doesn't support Proxies out of the box with the Fetch API currently

```js
import { fetch as undiciFetch, ProxyAgent } from 'undici';
import SmeeClient from "smee-client";

const myFetch = (url, options) => {
  return undiciFetch(url, {
    ...options,
    dispatcher: new ProxyAgent(<your_proxy_url>)
  })
}
const smee = new SmeeClient({
  source: 'https://smee.io/abc123',
  target: 'http://localhost:3000/events',
  logger: console,
  fetch: myFetch
})
```

This should be added to the README

**Comment by ftrahman** [comment]
where are we meant to pass the custom fetch wrapper to?

i tried the previous solution and ended up with a sea of errors.

**Comment by wolfy1339** [comment]
> where are we meant to pass the custom fetch wrapper to? smee.js?

Yes. That is what is indicated in the code example I shared


> i tried the previous solution and ended up with a sea of errors. 

Those packages are probably not compatible with the native Fetch API available in Node and instead use the Node HTTP API

**Comment by Uzlopak** [comment]
Actually the examply is not quite the recommended way by undici. 

You would use setGlobalDispatcher to set the proxy agent globally. Also there is EnvProxyAgent, which can handle the HTTP_PROXY and HTTPS_PROXY env variables. I have to look up if it is enabled by default now on node.js, but that was the desired behavior.

**Comment by wolfy1339** [comment]
> Actually the examply is not quite the recommended way by undici. 
> 
> You would use setGlobalDispatcher to set the proxy agent globally. Also there is EnvProxyAgent, which can handle the HTTP_PROXY and HTTPS_PROXY env variables. I have to look up if it is enabled by default now on node.js, but that was the desired behavior.

Undici probably updated since then, but my solution is backwards compatible to all NodeJS versions we support.

At the time of Node 18.0, there was no support for the `HTTP_PROXY` and `HTTPS_PROXY` env variables, nor was there an `EnvProxyAgent`

Besides, do we really want to include undici (which is a fairly large package) just to be able to have the proxy env variables?

**Comment by ftrahman** [comment]
even having tried your solution @wolfy1339, i am still receiving connection timeouts. this has been hindering me for a few days now

**Comment by wolfy1339** [comment]
What version are you running?

**Comment by ftrahman** [comment]
node is 18.20.2, smee is 2.0.2

**Comment by wolfy1339** [comment]
There is also another place you need to specify the proxy:
https://www.npmjs.com/package/eventsource#httphttps-proxy
