### ISSUE TITLE
How to log data received from smee server

### ISSUE THREAD

**Issue by PaddlePaddle-Gardener** [probot/smee-client#202]
I forwarded GitHub hook events through the Smee client, but my service's log showed that my service did not receive some events. I want to see if the Smee client received these data, but I did not see valid data in the Smee client log.

How to print the received data in smee client, pleeeeease.

**Comment by gr2m** [comment]
smee client logs requests using `console.info` by default
https://github.com/probot/smee-client/blob/587e09c6e509d995e210aa92771525639f3d2441/index.ts#L58

**Comment by Shaun2016** [comment]
All right, let me edit the code here~

**Comment by Shaun2016** [comment]
> smee client logs requests using `console.info` by default
> 
> https://github.com/probot/smee-client/blob/587e09c6e509d995e210aa92771525639f3d2441/index.ts#L58


All right, let me edit the code here~
