### ISSUE TITLE
What's the release system for `smee-client`?

### ISSUE THREAD

**Issue by oscard0m** [probot/smee-client#214]
I'm waiting for a new release of `smee-client` with the latest bump of some internal packages but seems to not be automatic.

What's the process? Why not use Semantic Releases with a Workflow as [it is done in `probot/probot`](https://github.com/probot/probot/blob/master/.github/workflows/release.yml)?

I would be happy to help in setting up an automated process for it.

_Originally posted by @oscard0m in https://github.com/probot/probot/discussions/1742_

**Comment by gr2m** [comment]
Is this blocking you? I could probably get the NPM_TOKEN, do you want to setup the semantic-release workflow? If there are no objections for anyone else, I'd say let's just go ahead and do it

**Comment by oscard0m** [comment]
Nothing critical but some outdated dependencies are conflicting with others, yep.

I will try to allocate some time tomorrow or during next week :)

**Comment by oscard0m** [comment]
Done :) https://github.com/probot/smee-client/pull/230
