### ISSUE TITLE
smee is down throwing 502

### ISSUE THREAD

**Issue by kamimanzoor** [probot/smee-client#225]
[smee](smee.io) is down and throwing 502 as shown in the attached screenshot.
![image](https://user-images.githubusercontent.com/16157737/197991189-a4d9c42a-febf-4c90-9749-fe5e4d8a0965.png)

Would greatly appreciate if you look into it soon. Thanks in advance :)

**Comment by Uzlopak** [comment]
This is a sporadic error. We are currently discussing the future of smee

https://github.com/probot/probot/pull/1921#issuecomment-1817184972
