### ISSUE TITLE
Cannot GET /abc123/api error

### ISSUE THREAD

**Issue by martina-if** [probot/smee-client#227]
Hi,

I am trying to test smee for delivering GH webhook events to my localhost server but I keep getting error pages like this:

```
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /abc123/api/catalog/entities</pre>
</body>
</html>
```

GH says it's unable to deliver the events and when I try curling it myself I get that error page from above.

I guess I am doing something obviously wrong but I can't find what. What it looks like is that smee client can't really connect to the channel?

This is how I ran it:

```
% smee -p 7009 -u https://smee.io/abc123
Forwarding https://smee.io/abc123 to http://127.0.0.1:7009/
Connected https://smee.io/abc123
```

**Comment by Uzlopak** [comment]
Closing because highly probable got irrelevant for OP.

**Comment by mcgear** [comment]
I am having the same issue with Deno, here is my startup:
```
const smee = new SmeeClient({
  source: "https://smee.io/<channel-id>",
  target: "http://localhost:8000",
  logger: console,
  fetch: true,
});

const events = smee.start();
```

Not sure what `highly probable got irrelevant for OP` means or how to fix.
