### ISSUE TITLE
Specifying the URL offered by Github in the "Details" link

### ISSUE THREAD

**Issue by RobMeades** [probot/smee-client#229]
We have SMEE running under Docker talking to a Jenkins agent running under Docker on a Docker network inside a completely closed/isolated system with static IP addresses; all is sweet.  When Github offers its "Details" link for a running Jenkins job, the base of the URL is to the static IP address/port of the Jenkins machine (e.g. `http://10.10.2.200:8080`); is there a way to display a different URL base here instead?

I ask because we only allow access to Jenkins via NGINX [configured to enforce client authentication] at a given URL (e.g. `https://our-test-system.redirectme.net`), so it would be nice, seamless in fact, if it were possible to offer that URL-base instead.

**Comment by kadler** [comment]
I think you need to configure that in Jenkins (if possible). Jenkins handles all of those details. AFAIK the only thing that smee should be involved in is forwarding the webhook coming *from* Jenkins.

**Comment by RobMeades** [comment]
The problem is that the SMEE client itself cannot use the external-access URL/port to Jenkins that someone browsing Github is required to use: we have set up that external-access URL/port to require client authentication (carried out during the HTTPS handshake) so that access to Jenkins from the public internet is secured.

As far as I am aware the SMEE client cannot respond to a client authentication request during HTTPS handshake (?); that is why it uses a different port and the static IP address of Jenkins, which is running in another Docker container on the same machine.  And it is that internal static IP address/port the what ends up being displayed on Github.

**Comment by RobMeades** [comment]
Weehee, you're absolutely right, I can just change the `Jenkins URL` field to get the desired result.  The Jenkins configuration page tells me that my reverse proxy setup is broken, because Jenkins also can't get to that URL, but I can dismiss the warning and everything appears to work.

Many thanks for the tip!
