### ISSUE TITLE
Version 1.2.5 broken?

### ISSUE THREAD

**Issue by ulfmansson** [probot/smee-client#269]
When I installed version 1.2.5 it looks like it doesn't use any of the arguments

$ /usr/bin/smee -u http://my-smee.example.com/i0siaopadscd --path /github-webhook/ --port 8080
Forwarding https://smee.io/XFXHGJclYB3tY5uZ to http://127.0.0.1:undefinedundefined
Connected https://smee.io/XFXHGJclYB3tY5uZ
^C
$ sudo npm install -g smee-client@1.2.3
/usr/bin/smee -> /usr/lib/node_modules/smee-client/bin/smee.js
+ smee-client@1.2.3
added 5 packages from 2 contributors and updated 4 packages in 2.649s
$ sudo /usr/bin/smee -u http://my-smee.example.com/i0siaopadscd --path /github-webhook/ --port 8080
Forwarding http://my-smee.example.com/i0siaopadscd to http://127.0.0.1:8080/github-webhook/
Connected http://my-smee.example.com/i0siaopadscd

**Comment by Uzlopak** [comment]
How about using v2.0.0?

**Comment by Uzlopak** [comment]
v1.2.5 is basically v1.2.3. Please use v2.0.0
