### ISSUE TITLE
[Question] Sniff data with multiple clients

### ISSUE THREAD

**Issue by LucBerge** [probot/smee-client#279]
I want to use Smee to forward payloads containing sensitive datas (email, passwords, personal informations).
What happens if a malicious user get access to my smee url `https://smee.io/abcd` (by pushing it to Github for example).

**He can listen to payloads without me to known it and access to user sensitive datas.**

**Do you plan to do something for this use case ?
Limit the number of client to 1 ?
Whitelist the client IP ?**

**Comment by AaronDewes** [comment]
This is not planned currently, please have a look at the server FAQ at https://github.com/probot/smee.io.

**Comment by LucBerge** [comment]
> you should not use it in production

Yes I know but this is a legitim question

**Comment by Uzlopak** [comment]
We dont plan any changes regarding this.
