### ISSUE TITLE
beta version of smee-client fails with runtime error using --help flag

### ISSUE THREAD

**Issue by Dancho80** [probot/smee-client#316]
I am encountering a runtime error with the beta version of smee-client both when installing from npm (npm i smee-client@3.0.0-beta.3) and when building the beta branch from source. The error occurs when I try to run a simple command like smee --help.

**Error:**
`
const { program } = require('commander')
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/smee-client/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
`

**Environment:**
Tried with Node.js 18 and Node.js 22 (same result)
Installed via npm i smee-client@3.0.0-beta.3
Also tried building the beta branch from source with npm install and npm run build.

**Steps to reproduce:**
Install the beta version via clone the repository and build the beta branch.
Run ./bin/smee.js --help

**Comment by wolfy1339** [comment]
Can you post the full stack trace with the numbers?

I don't see any `require()` anywhere in the source

**Comment by wolfy1339** [comment]
Thanks that makes more sense.

We haven't gotten around to updating that file yet.

**Comment by Dancho80** [comment]
Do you have any ETA for a fix? Proxy support is essential for our use case, and using smee is a great solution for us. We'd appreciate any updates or guidance on when this issue might be resolved. Maybe some workaround we can try locally?

**Comment by wolfy1339** [comment]
The fix is really easy, it consists of changing all `require()` to `import`, using `fs.readFile()` and `JSON.parse()`, using full relative paths (can't import a directory in ESM, you have to import a file)

It's a 5 minute fix at the most, I can push it soon.

I will also try to push a fix for the `master` branch for proxy support.

**Comment by wolfy1339** [comment]
Can you test the new version
https://github.com/probot/smee-client/releases/tag/v3.0.0-beta.4

**Comment by Dancho80** [comment]
hi
i tested the newer version with a webhook of GitHub PR comment.
Getting an error:
TypeError: Cannot convert argument to a ByteString because the character at index 10117 has a value of 8482 which is greater than 255.
    at Client.fetch (/smee-client/node_modules/undici/index.js:112:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.onmessage (file:///smee-client/index.js:52:30)

**Comment by wolfy1339** [comment]
I can't reproduce that error

**Comment by Dancho80** [comment]
it works fine with the https://smee.io/<my_channel> but fails on self hosted smee server. I deployed it from master branch on https://github.com/probot/smee.io .

any known issue with self deployed servers that might result such an error?

**Comment by wolfy1339** [comment]
I'm not sure where the problem would lie. I don't currently have any idea why it would fail like that.

It would require some more debugging

**Comment by Dancho80** [comment]
with some AI help: 

> the issue typically occurs when you're trying to send or process data that includes non-ASCII characters (e.g., special symbols or unicode characters).

and indeed, in my test with a self hosted server, I used some private repository that one of the fields contains a "registered trademark symbol" ®

so probably the smee client doesn't handle such chars properly and crushes. 
maybe some UTF-8 encoding should be added to header and body?

**Comment by Dancho80** [comment]
thanks! closing that issue. will open a new one for a "character at index wrong value"
