### ISSUE TITLE
Types for smee-client

### ISSUE THREAD

**Issue by bkeepers** [probot/smee-client#74]
It would be great to have TypeScript types for `smee-client`.

**Comment by macklinu** [comment]
I noticed that probot core was rewritten in TypeScript (https://github.com/probot/probot/pull/372). Is there a larger desire to convert other apps / parts of the `@probot` organization's repos (like smee) to TypeScript also, or just to provide types?

**Comment by JasonEtco** [comment]
for sure - I think the plan in #87 is to make this repo `smee-client`, so its actually already in the right place.

**Comment by wolfy1339** [comment]
Not stale
________________________________

**Comment by JasonEtco** [comment]
Now that #93 is merged, we can start thinking about this more practically! We can convert the library to TypeScript, or just add types - either way works for me. Marking this as `help wanted` to make it clear that it'd be open to PRs! I think adding types would be a good first step, but there's not so much code that converting to TS would be too rough.

**Comment by wolfy1339** [comment]
Not stale
________________________________

**Comment by wolfy1339** [comment]
Not stale. Waiting on input from maintainers
________________________________

**Comment by wolfy1339** [comment]
Not stale

**Comment by wolfy1339** [comment]
still relevant

**Comment by wolfy1339** [comment]
Not stale. Still relevant. Is nobody looking through issues in this repo?

**Comment by pravinblaze** [comment]
Thanks @gr2m  :)

**Comment by gr2m** [comment]
I didn't do much, all @wolfy1339's work, and patience :)
