### ISSUE TITLE
Events not sent by GitHub don't pass duplicate event handling in the browser

### ISSUE THREAD

**Issue by 0xR** [probot/smee-client#76]
I'm starting a new smee channel and I'm posting to it using httpie:
```
http post https://smee.io/UH59iRnWg39hD3Zk asdfasdf=asdf
```

This event shows up
![image](https://user-images.githubusercontent.com/6420016/45265146-29194600-b447-11e8-97be-af5e6b1e88cf.png)

But when I try again, no new event shows up until I clear the smee channel.
![image](https://user-images.githubusercontent.com/6420016/45265158-5239d680-b447-11e8-8525-216259cb16d2.png)

**Comment by 0xR** [comment]
Not really, I was looking for a generic "Webhook payload delivery service". I know smee from developing github bots, but since the website doesn't mention github too prominently I thought it would work for any webhook. Note github not being mentioned:
![image](https://user-images.githubusercontent.com/6420016/45280204-c457fd00-b4d3-11e8-9ed5-b6bf9c9a6bbc.png)

What makes it further confusing is that it will display the first webhook payload, even though it doesn't have an github event id. This really convinced me I could use smee for any webhook.

Tbh, if would not deduplicate if the github id is missing it would already be a generic webhook payload delivery service.

What I ended up with is running request-bin locally in docker and using ngrok. Ths works, but a public webhook service would still be nice.

**Comment by JasonEtco** [comment]
I'd still be interested in making this work!

**Comment by andy-g** [comment]
I've created a PR (#94) to hopefully implement this suggestion.

**Comment by JasonEtco** [comment]
Closed by #94, thanks @andy-g!
