### ISSUE TITLE
Connection timeout when connecting to smee under proxy

### ISSUE THREAD

**Issue by kshitij10496** [probot/smee-client#84]
I've been looking to try smee while developing a GitHub app.

```shell
$ smee -u https://smee.io/ufFwqO3nnPuM0B -p 8888                                                                                            
Forwarding https://smee.io/ufFwqO3nnPuM0B to http://127.0.0.1:8888/
Event {
  type: 'error',
  message: 'connect ETIMEDOUT xx.xx.xxx.xxx:xxx' }
```

Currently, I'm working behind a proxy server which I have set for the shell and npm.
This probably is causing the connection issue as I'm able to connect to smee when I'm not using the proxy server. How do I solve the connection timeout issue under proxy?

**Comment by GitMylou** [comment]
Hello,
I just had the same issue. 
Looking at smee/index.js, the eventSource is build like that:
const events = new EventSource(this.source)

But according to eventSource documentation, it is possible to add proxy. "This is typically useful if you are behind a corporate firewall."

new EventSource(url, {proxy: 'http://your.proxy.com'});

https://github.com/EventSource/eventsource/blob/master/README.md

**Comment by JasonEtco** [comment]
Thanks for that doc link @GitMylou - I think a `--proxy` option might be useful in `smee-client`. That'd go somewhere here:

https://github.com/probot/smee/blob/9dc32b0be76771a731f661fd39d6b5acdec1e3a4/client/bin/smee.js#L7-L13

And be passed down here:

https://github.com/probot/smee/blob/9dc32b0be76771a731f661fd39d6b5acdec1e3a4/client/index.js#L45

Anyone up for opening a PR? ❤️

**Comment by Dancho80** [comment]
any progress with that PR to enable a client usage behind the proxy?
Currently, it's a show stopper for us to use this great project :(

**Comment by pdpdvp** [comment]
<img width="1028" alt="Screen Shot 2020-08-17 at 9 48 44 AM" src="https://user-images.githubusercontent.com/22753151/90410789-6b565380-e070-11ea-9748-7de2452aaf32.png">

Im seeing this continuous timeout errors in the logs, my app internally makes api calls to Jira and Cruicble. Can anyone help me understanding what is the issue?

**Comment by mfaltas-sandia** [comment]
> 
> 
> Hello,
> I just had the same issue.
> Looking at smee/index.js, the eventSource is built like that:
> const events = new EventSource(this.source)
> 
> But according to eventSource documentation, it is possible to add proxy. "This is typically useful if you are behind a corporate firewall."
> 
> new EventSource(url, {proxy: '[http://your.proxy.com'}](http://your.proxy.com'%7D));
> 
> https://github.com/EventSource/eventsource/blob/master/README.md

I have tried doing: const es = new EventSource(this.source, {proxy: 'http://your.proxy.com'});

and I end up getting "Bad Request" "Error 400" instead of the connection timeout errors. Any advice on what I can do to fix this?
