### ISSUE TITLE
Commit package-lock.json

### ISSUE THREAD

**Issue by macklinu** [probot/smee-client#90]
_Originally posted by @JasonEtco in https://github.com/probot/smee/pull/86#issuecomment-447961638_

This would probably be good to tackle after #86 is merged, since that PR updates a handful of dependencies.

**Comment by macklinu** [comment]
I think this is unblocked now that #86 is merged. /cc @JasonEtco for further input

**Comment by JasonEtco** [comment]
This is definitely unblocked now, especially now that #93 is done! Let's do it!
